CREATE DATABASE rosdb;

USE rosdb;

CREATE TABLE turtlepos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    theta FLOAT NOT NULL,
    time DATETIME DEFAULT CURRENT_TIMESTAMP
);